### ISSUE TITLE
EN to JA not working

### ISSUE THREAD

**Issue by kijeEnki** [xunmengshe/PhonemizerOnUtau#4]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

other phonemizers work but EN to JA doesn't.

### Explains how to reproduce the bug

1. try to use the EN to JA phonemizer

### OS & Version

Windows 11

### Logs

`Using phonemizer [EN to JA] English to Japanese Phonemizer (Contributed by TUBS)
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenUtau.Core.DocManager.ExecuteCmd(UCommand cmd) in D:\a\PhonemizerOnUtau\PhonemizerOnUtau\OpenUtau.Core\DocManager.cs:line 178
   at OpenUtau.Api.Phonemizer.OnAsyncInitStarted() in D:\a\PhonemizerOnUtau\PhonemizerOnUtau\OpenUtau.Core\Api\Phonemizer.cs:line 223
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.ReadDictionaryAndInit() in D:\a\PhonemizerOnUtau\PhonemizerOnUtau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 685
   at OpenUtau.Plugin.Builtin.SyllableBasedPhonemizer.SetSinger(USinger singer) in D:\a\PhonemizerOnUtau\PhonemizerOnUtau\OpenUtau.Plugin.Builtin\SyllableBasedPhonemizer.cs:line 222
   at Program.<Main>$(String[] args) in D:\a\PhonemizerOnUtau\PhonemizerOnUtau\PhonemizerOnUtau\Program.cs:line 124`

**Comment by kijeEnki** [comment]
en x-sampa doesn't work as well

**Comment by oxygen-dioxide** [comment]
This bug is fixed in 0.0.2
